language: node_js
node_js:
  - node
  - 10
branches:
  only:
    - develop
install:
  - npm install
cache:
  directories:
    - node_modules

script:
  - npm run test:coveralls
  - npm run test
after_success:
  - npm run coverage 
  - npm run coveralls